nodeLinker: node-modules

npmRegistries:
  "https://mc-domain-252355243038.d.codeartifact.us-east-1.amazonaws.com/npm/mc-components/":
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN:-}"

npmPublishRegistry: "https://mc-domain-252355243038.d.codeartifact.us-east-1.amazonaws.com/npm/mc-components/"