definitions:
  caches:
    node:
      key:
        files:
          - yarn.lock
      path: node_modules
    dist-storybook: dist-storybook

pipelines:
  pull-requests:
    default:
      - step:
          name: Prep Deps
          image: node:22
          caches:
            - node
          script:
            - corepack enable
            - yarn set version stable
            - yarn
      - parallel:
          - step:
              name: Lint
              image: node:22
              caches:
                - node
              script:
                - yarn prettier '*.{.ts,scss,css,html}' --check
                - yarn eslint . --ext ts
          - step:
              name: Test
              image: node:22
              caches:
                - node
              script:
                - yarn test
          - step:
              name: e2e
              image: mcr.microsoft.com/playwright:v1.50.1-noble
              caches:
                - node
              script:
                - yarn test:playwright
          - step:
              name: Build
              image: node:22
              caches:
                - node
              script:
                - yarn build
  branches:
    main:
      - step:
          name: Prep Deps
          image: node:22
          caches:
            - node
          script:
            - yarn set version stable
            - yarn
      - parallel:
          - step:
              name: Lint
              image: node:22
              caches:
                - node
              script:
                - yarn prettier '*.{.ts,scss,css,html}' --check
                - yarn eslint . --ext ts
          - step:
              name: Test
              image: node:22
              caches:
                - node
              script:
                - yarn test
          - step:
              name: e2e
              image: mcr.microsoft.com/playwright:v1.50.1-noble
              caches:
                - node
              script:
                - yarn test:playwright
          - step:
              name: Build
              image: node:22
              caches:
                - node
                - dist-storybook
              script:
                - yarn build
      - step:
          name: Publish S3 - Get Code Artifact Token
          trigger: manual
          image: amazon/aws-cli
          caches:
            - dist-storybook
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

            - aws s3 sync dist-storybook s3://mc-storybook-bucket

            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $MC_COMPONENTS_DOMAIN --domain-owner $MC_COMPONENTS_DOMAIN_OWNER --region $AWS_DEFAULT_REGION --query authorizationToken --output text`

            - echo "export CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> token.sh
          artifacts:
            - token.sh
      - step:
          name: Publish CodeArtifact
          deployment: Prod
          trigger: manual
          image: node:22
          caches:
            - node
          script:
            - source token.sh
            - yarn publish
