pipelines:
  branches:
    main:
      - step:
          name: Lint
          image: node:20
          caches:
            - node
          script:
            - yarn install
            - npx eslint .
      - step:
          name: Built
          image: node:20
          script:
            - yarn build
          caches:
            - node
      - step:
          name: setup
          image: atlassian/pipelines-awscli
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - aws codeartifact get-authorization-token --domain XXXXX --domain-owner XXXXXx --query authorizationToken --output text > pass.txt
            - value=$(<pass.txt)
            - echo $value
            - echo "export CODEARTIFACT_AUTH_TOKEN=$value" set_env.sh

            - printenv > set_env.sh

          artifacts:
            - set_env.sh
      - step:
          name: Publish
          image: node:20
          caches:
            - node
          script:
            - source set_env.sh
            - yarn version --pre --major
            - yarn publish
