definitions:
  caches:
    node:
      key:
        files:
          - yarn.lock
      path: node_modules

pipelines:
  pull-requests:
    default:
      - step:
          name: Prep Deps
          image: node:22
          caches:
            - node
          script:
            - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
            - yarn
      - parallel:
          - step:
              name: Lint
              image: node:22
              caches:
                - node
              script:
                - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
                - yarn prettier '*.{.ts,scss,css,html}' --check
                - yarn eslint . --ext ts
          - step:
              name: Test
              image: node:22
              caches:
                - node
              script:
                - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
                - yarn test
          - step:
              name: Build
              image: node:22
              caches:
                - node
              script:
                - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
                - yarn build
  branches:
    main:
      - step:
          name: Prep Deps
          image: node:22
          caches:
            - node
          script:
            - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
            - yarn
      - parallel:
          - step:
              name: Lint
              image: node:22
              caches:
                - node
              script:
                - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
                - yarn prettier '*.{.ts,scss,css,html}' --check
                - yarn eslint . --ext ts
          - step:
              name: Test
              image: node:22
              caches:
                - node
              script:
                - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
                - yarn test
          - step:
              name: Build
              image: node:22
              caches:
                - node
              script:
                - export CODEARTIFACT_AUTH_TOKEN="CODEARTIFACT_AUTH_TOKEN"
                - yarn build
      - step:
          name: Get Token
          deployment: Prod
          trigger: manual
          image: amazon/aws-cli
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $MC_COMPONENTS_DOMAIN --domain-owner $MC_COMPONENTS_DOMAIN_OWNER --region $AWS_DEFAULT_REGION --query authorizationToken --output text`

            - yum install https://rpm.nodesource.com/pub_21.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
            - yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
            
            - npm install --global yarn

            - yarn publish
            - aws s3 sync dist-storybook s3://mc-storybook-bucket

      #       - echo "export CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> token.sh
      #     artifacts:
      #       - token.sh
      # - step:
      #     name: Publish CodeArtifact
      #     deployment: Prod
      #     trigger: manual
      #     image: node:22
      #     caches:
      #       - node
      #     script:
      #       - source token.sh
      #       - yarn publish
      #       - aws s3 sync dist-storybook s3://mc-storybook-bucket
