pipelines:
  branches:
    main:
      # - step:
      #     name: Lint
      #     image: node:20
      #     caches:
      #       - node
      #     script:
      #       - yarn
      #       - yarn lint
      # - step:
      #     name: Built
      #     image: node:20
      #     script:
      #       - yarn build
      #     caches:
      #       - node
      #     artifacts:
      #       - dist/** 
      - step:
          name: Get Token
          image: atlassian/pipelines-awscli
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $MC_COMPONENTS_DOMAIN --domain-owner $MC_COMPONENTS_DOMAIN_OWNER --region $AWS_DEFAULT_REGION --query authorizationToken --output text`

            - echo "export CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> token.sh
          artifacts:
            - token.sh
      - step:
          name: Publish
          image: node:20
          caches:
            - node
          script:
            - source token.sh
            # - export $(cat token.txt | xargs)
            # - echo "_auth=$CODEARTIFACT_AUTH_TOKEN" >> .npmrc
            # - cat .npmrc
            - yarn build

            - yarn config set npmRegistryServer "https://mc-components-252355243038.d.codeartifact.us-east-1.amazonaws.com/npm/main/"

            - yarn config set 'npmRegistries["https://mc-components-252355243038.d.codeartifact.us-east-1.amazonaws.com/npm/main/"].npmAuthToken' "${CODEARTIFACT_AUTH_TOKEN}"

            - yarn config set 'npmRegistries["https://mc-components-252355243038.d.codeartifact.us-east-1.amazonaws.com/npm/main/"].npmAlwaysAuth' "true"

            - yarn version --pre --major
            - yarn publish --verbose
