region                 = "us-east-1"
domain_name            = "mc-components"
encryption_key         = "arn:aws:kms:us-east-1:123456789012:key/def456"
repository_name        = "prod"
description            = "Production repository"
codeartifact_read_key  = "dev-read-key"
codeartifact_write_key = "dev-write-key"
