name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            dist-storybook/
          retention-days: 30

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.dist
            dist-storybook
          key: dist-${{ runner.os }}-${{ hashFiles('dist/') }}

  format:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Format Check
        run: yarn prettier '*.{ts,scss,css,html}' --check

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Lint
        run: yarn eslint . --ext ts

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Unit Tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 30

  # e2e:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup
  #       with:
  #         node-version: "22.x"

  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps

  #     - name: Run Playwright Tests
  #       run: yarn test:e2e --max-failures=1

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
