name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CODE_ARTIFACT_DOMAIN: mc-domain
  CODE_ARTIFACT_DOMAIN_OWNER: 252355243038

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            dist-storybook/
          retention-days: 30

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Format Check
        run: yarn prettier '*.{ts,scss,css,html}' --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Lint
        run: yarn eslint . --ext ts

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Unit Tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 30

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: yarn test:e2e --max-failures=1

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deployment:
    needs: [build, format, lint, test, e2e]
    runs-on: ubuntu-latest
    environment: Prod

    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Publish to S3
        run: aws s3 sync dist-storybook s3://mc-storybook-bucket

      - name: Publish to CodeArtifact
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $CODE_ARTIFACT_DOMAIN --domain-owner $CODE_ARTIFACT_DOMAIN_OWNER --region $AWS_REGION --query authorizationToken --output text)
          yarn npm publish
