name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            dist-storybook/
          retention-days: 30

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Prettier Format Check
        run: yarn prettier '*.{ts,scss,css,html}' --check

  tf-format:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.4"

      - name: Terraform Format Check
        run: terraform fmt -recursive -check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Lint
        run: yarn eslint . --ext ts

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Unit Tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 30

  e2e:
    needs: build
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.0-jammy
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Run Playwright Tests
        run: yarn test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --max-failures=1

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 5

  trivy:
    needs: [e2e, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
          scan-type: 'fs'
          scan-ref: '.'

  snyk:
    needs: [e2e, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonarqube:
    needs: [e2e, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.terraform.provider.version=1.10.4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  check-version:
    # needs: [build, prettier, tf-format, lint, test, e2e, trivy, snyk, sonarqube]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      # - name: Download previous version artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: previous-deployed-version

      - name: Get previous version
        run: |
          PREV_COMMIT=$(git rev-parse HEAD~1)
          git show $PREV_COMMIT:package.json > prev_package.json

      - id: verify-version
        name: Check package version
        run: | 
          VERSION1=$(yarn node -p "require('./package.json').version")
          VERSION2=$(yarn node -p "require('./prev_package.json').version")

          echo "Version 1: $VERSION1"
          echo "Version 2: $VERSION2"

          if [[ "$VERSION1" == "$VERSION2" ]]; then
            echo "isSameVersion=true" >> "$GITHUB_OUTPUT"
          else
            echo "isSameVersion=false" >> "$GITHUB_OUTPUT"
          fi
        
      - name: Check package version
        if: steps.verify-version.outputs.isSameVersion == 'true'
        run: echo "::warning::You must increment the version in package.json"

  approval:
    needs: [build, prettier, tf-format, lint, test, e2e, trivy, snyk, sonarqube]
    # needs: [check-version]
    runs-on: ubuntu-latest

    steps:
      - uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ github.token }}
          approvers: Kevinoob-design
          minimum-approvals: 1
          issue-title: "Deploying to prod"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
          timeout-minutes: 10

  deployment:
    env:
      AWS_REGION: ${{vars.AWS_REGION}}
      CODE_ARTIFACT_DOMAIN: ${{vars.CODE_ARTIFACT_DOMAIN}}
      CODE_ARTIFACT_DOMAIN_OWNER: ${{vars.CODE_ARTIFACT_DOMAIN_OWNER}}

    needs: [approval]
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Publish to CodeArtifact
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $CODE_ARTIFACT_DOMAIN --domain-owner $CODE_ARTIFACT_DOMAIN_OWNER --region $AWS_REGION --query authorizationToken --output text)
          yarn npm publish

      - name: Publish to S3
        run: aws s3 sync dist-storybook s3://mc-storybook-bucket

      # - name: store deployed version
      #   run: |
      #     yarn node -p "require('./package.json').version > previous-deployed-version

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: version-artifact
      #     path: |
      #       previous-deployed-version