name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  format:
    needs: [build]
    uses: ./.github/workflows/prettier.yml

  terraform:
    needs: [build]
    uses: ./.github/workflows/tf-format.yml

  lint:
    needs: [build]
    uses: ./.github/workflows/lint.yml

  test:
    needs: [format, terraform, lint]
    uses: ./.github/workflows/test.yml

  e2e:
    needs: [format, terraform, lint]
    uses: ./.github/workflows/e2e.yml

  e2e-merge-report:
    needs: [e2e]
    uses: ./.github/workflows/e2e-merge-report.yml

  trivy:
    needs: [e2e, test]
    uses: ./.github/workflows/trivy.yml

  snyk:
    needs: [e2e, test]
    secrets: inherit
    uses: ./.github/workflows/snyk.yml

  sonarqube:
    needs: [e2e, test]
    secrets: inherit
    uses: ./.github/workflows/sonarqube.yml

  codeql:
    needs: [e2e, test]
    uses: ./.github/workflows/codeql.yml

  deployment:
    needs: [trivy, snyk, sonarqube, codeql]
    secrets: inherit
    uses: ./.github/workflows/deployment.yml