name: Deployment

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{vars.AWS_REGION}}
  CODE_ARTIFACT_DOMAIN: ${{vars.CODE_ARTIFACT_DOMAIN}}
  CODE_ARTIFACT_DOMAIN_OWNER: ${{vars.CODE_ARTIFACT_DOMAIN_OWNER}}

jobs:
    deployment:
        runs-on: ubuntu-latest
        environment: Prod
    
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/setup
            with:
              node-version: "22.x"
    
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}
    
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: build-artifact
    
          - name: Publish to S3
            run: aws s3 sync dist-storybook s3://mc-storybook-bucket
    
          - name: Publish to CodeArtifact
            run: |
              export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $CODE_ARTIFACT_DOMAIN --domain-owner $CODE_ARTIFACT_DOMAIN_OWNER --region $AWS_REGION --query authorizationToken --output text)
              yarn npm publish