name: "Playwright E2E"

on:
  workflow_call: 

jobs:
  playwright:
    container: mcr.microsoft.com/playwright:v1.50.0-jammy
    timeout-minutes: 10

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Run Playwright Tests
        run: yarn test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --max-failures=1

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1